/*
PRIMITIVOS (IMUTÁVEIS) - STRING , NUMBER, BOONLEAN, UNDEFINED, NULL (BIGINT,SYMBOL) - VALORES COPIADOS

REFERÊNCIA (MUTÁVEL) - ARRAY, OBJECT, FUNCTION - PASSADOS POR REFERÊNCIA (APONTA O MESMO LUGAR NA MEMÓRIA)
*/
let a = [1,2,3];
let b = [...a]; //ASSIM SE COPIA INVÉS DE APONTAR PARA O MESMO LUGAR NA MEMÓRIA

const c = {
    nome: 'Luan',
    sobrenome: 'Victor'
};
const d = {...c};